# Made by @helloji123bot. Keep credits cause it hurts...
# Noice plugin.. Modified by @hellboi_atul for DARK COBRA..but the main credit goes to the owner who made it..
# Random Chat Number Added by @Anonymous_machinee

import random, re
from userbot.utils import admin_cmd
import asyncio
from telethon import events

@borg.on(admin_cmd(pattern="fgben"))
async def _(event):
     if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await event.edit("Preparing to gban this nub nibba....")
        await asyncio.sleep(2)
        await event.edit("Gbanning user.....")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 1 chats")
        await asyncio.sleep(2)
        a=random.randrange(2,5)
        await event.edit(f"Gbanning user... \n {a} chats")
        await asyncio.sleep(2)
        b=random.randrange(6,10)
        await event.edit(f"Gbanning user... \n {b} chats")
        await asyncio.sleep(2)
        c=random.randrange(11,15)
        await event.edit(f"Gbanning user... \n {c} chats")
        await asyncio.sleep(2)
        d=random.randrange(16,20)
        await event.edit(f"Gbanning user... \n {d} chats")
        await asyncio.sleep(2)
        e=random.randrange(21,25)
        await event.edit(f"Gbanning user... \n {e} chats")
        await asyncio.sleep(2)
        f=random.randrange(26,30)
        await event.edit(f"Gbanning user... \n {f} chats")
        await asyncio.sleep(2)
        g=random.randrange(31,35)
        await event.edit(f"Gbanning user... \n {g} chats")
        await asyncio.sleep(2)
        h=random.randrange(36,43)
        await event.edit(f"Gbanning user... \n {h} chats")
        await asyncio.sleep(2)
        i=random.randrange(44,48)
        await event.edit(f"Gbanning user... \n {i} chats")
        await asyncio.sleep(2)
        j=random.randrange(49,55)
        await event.edit(f"Gbanning user... \n {j} chats")
        await asyncio.sleep(2)
        k=random.randrange(56,60)
        await event.edit(f"Gbanning user... \n {k} chats")
        await asyncio.sleep(2)
        l=random.randrange(61,65)
        await event.edit(f"Gbanning user... \n {l} chats")
        await asyncio.sleep(2)
        m=random.randrange(66,70)
        await event.edit(f"Gbanning user... \n {m} chats")
        await asyncio.sleep(2)
        n=random.randrange(71,75)
        await event.edit(f"Gbanning user... \n {n} chats")
        await asyncio.sleep(2)
        o=random.randrange(76,80)
        await event.edit(f"Gbanning user... \n {o} chats")
        await asyncio.sleep(2)
        p=random.randrange(81,85)
        await event.edit(f"Gbanning user... \n {p} chats")
        await asyncio.sleep(2)
        q=random.randrange(86,93)
        await event.edit(f"Gbanning user... \n {q} chats")
        await asyncio.sleep(2)
        r=random.randrange(94,96)
        await event.edit(f"Gbanning user... \n {r} chats")
        await asyncio.sleep(2)
        s=random.randrange(97,100)
        await event.edit(f"Gbanning user... \n {s} chats")
        await asyncio.sleep(2)
        t=random.randrange(100,105)
        await event.edit(f"Gbanning user... \n {t} chats")
        await asyncio.sleep(2)
        u=random.randrange(106,110)
        await event.edit(f"Gbanning user... \n {u} chats")
        await asyncio.sleep(2)
        v=random.randrange(110,115)
        await event.edit(f"Gbanning user... \n {v} chats")
        await asyncio.sleep(2)
        w=random.randrange(116,120)
        await event.edit(f"Gbanning user... \n {w} chats")
        await asyncio.sleep(2)
        await event.edit(f"Gbanning user... \n 125 chats")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 130 chats")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 135 chats")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 140 chats")
        await asyncio.sleep(2)
        x=random.randrange(140,146)
        await event.edit(f"Gbanning user... \n {x} chats")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 150 chats")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 158 chats")
        await asyncio.sleep(2)
        y=random.rangrange(158,165)
        await event.edit(f"Gbanning user... \n {y} chats")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 170 chats")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 177 chats")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 180 chats")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 185 chats")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 190 chats")
        await asyncio.sleep(2)
        z=random.randrange(191,200)
        await event.edit(f"Gbanning user... \n {z} chats")
        await asyncio.sleep(2)
        await event.edit("Gbanning user... \n 204 chats")
        await asyncio.sleep(1.5)
        await event.edit("Gbanned this nub nibba successfully in😏: 204 chats.\nBlocked and added to gban watch!")
  
     
        
@borg.on(admin_cmd(pattern="fungben ?(.*)"))
async def _(event):
     if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await event.edit("Preparing to Ungban this nub nibba please weit for a while.....")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user.....")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 1 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 5 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 10 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 15 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 20 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 25 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 30 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 35 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 40 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 45 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 50 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 55 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 60 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 65 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 70 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 75 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 80 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 85 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 90 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 95 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 100 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 105 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 110 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 115 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 120 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 125 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 130 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 135 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 140 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 145 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 150 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 155 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 160 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 165 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 170 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 175 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 180 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 185 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 190 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 200 chats")
        await asyncio.sleep(2)
        await event.edit("UnGbanning user... \n 204 chats")
        await asyncio.sleep(1.5)
        await event.edit("UnGbanned this nub nibba successfully in 204 chats.\nUnBlocked and removed from gban watch")
